# Generated by Django 5.1.2 on 2024-10-09 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('restaurant', '식당'), ('cafe', '카페'), ('park', '공원'), ('movie', '영화관'), ('activity', '액티비티'), ('other', '기타')], max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='date_places/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.dateplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kakaouser')),
            ],
        ),
    ]
